language: generic
deploy:
  provider: s3
  access_key_id: AKIAIHA424WLJR5RGMYQ
  secret_access_key:
    secure: "pG3tBAgUtZ4jrbHFh3iHjCAl4+w64vb3WPhJS8ZVQpb6xdynM48EhegcsXDtIZfZrb22wAiDFWF92AW1IxozcoTscCdGa02PuCMFCfSS2JzmFUZNc9ZQhd4MwtDSrZzjjnnCG1CK+ImpXz7U2gLkIH8sNtaHiJX6bVexhtA0opNP86JIS89xpe8kFpRqGb2JibScwbkMAC6t70lNybYzUH9Xghk/tfWKx01Nk9HiBvoHAl1uPAgxfRW3yGMoXwmutz6Upi1/v/5/Dv4nFhO9H8zf9urUlqt4enUZRE77jeli+Vevw/od9Lv+NLQCQETnSldrmRtJhLP7dP2Js4ODNU3G6npYQAe/XdaRhttZLJ1d6WtmPSgte5JlGiO/MJsrVf3c8LCcgwiA+RqWcoyXIJHS5Pjsi7Xj8YBlawAMMqeGbQD0UitB/8SIIAGhdu6MhKg66BUz0LjMlVOIjJ4QuXLqQmF53qGLYL2glAtoR3HfZenM6ayXJsXl6575PRXIyMNyH6E5YNEAQ8SxSjS2B3NNYW8o2mcdCWvICVEf6RuqppWCUcOsauIO4/fCBG8YRtxSjuTpecI6x8tlBSbjmt3dYbF8QCiYvBGDOjc+AOaDb3Qw1JwuxLgstGHFMvM8as3sOBbhZbaN8wACvAHallxpW3oY+9G5M4Bm1awTmhw="
  bucket: "elasticbeanstalk-us-west-2-893554244568"
  skip_cleanup: true
  region: "us-west-2"
  upload-dir: projects
  acl: public_read